Repository keironchaudhry/js-game-project, pull requests merged in 2023-05, with the labels that each got.

#1 Keiron: Setup and initialize project
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement, frontend, backend

#2 Setup: Import Kaboom.js into project + test
  assets/js/script.js
  index.html
Labels: enhancement, frontend, backend

#16 Edit: Set up Kaboom.js file + create sprites folder + add Yoduh sprite
  assets/css/style.css
  assets/js/script.js
  assets/sprites/yoda-1.png
  assets/sprites/yoda-2.png
  assets/sprites/yoda-3.png
  assets/sprites/yoda-4.png
  assets/sprites/yoda-halt.png
  assets/sprites/yoda-jump-down.png
  assets/sprites/yoda-jump.png
  assets/sprites/yoda-reach-2.png
  assets/sprites/yoda-reach.png
  index.html
Labels: frontend

#21 Feat: Create game narrative document
  documentation/game_narrative.md
Labels: documentation

#22 Task: Background design
  assets/background/tiled-background-yoduh.png
Labels: frontend

#23 Add: Navbar with icon and an options button
  assets/css/style.css
  assets/sprites/heart.png
  index.html
Labels: frontend

#24 Feat: Creation of life containers + js logic
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: frontend

#25 Edit: Style background to correct position to begin a base for testin…
  assets/css/style.css
  index.html
Labels: frontend

#27 Resolved: Issue regarding components not being recognised resolved
  assets/background/ground.png
  assets/background/hello.jpg
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: bug
